const PLDR_MOCK_DATA = {
  stats: [
    { id: "new", label: "新材料", value: 7, delta: "3 项可审", tone: "cyan", route: "review", filter: "new" },
    { id: "changed", label: "网页变化", value: 3, delta: "2 项重要", tone: "amber", route: "changes" },
    { id: "review", label: "待处理", value: 5, delta: "3 可审 · 2 故障", tone: "purple", route: "review" },
    { id: "failed", label: "来源失败", value: 2, delta: "均在重试", tone: "red", route: "sources", filter: "failed" },
  ],
  attention: [
    {
      id: "att-sca",
      kind: "change",
      priority: "high",
      title: "苏伊士运河管理局通告发生实质变化",
      source: "Suez Canal Authority",
      time: "18 分钟前",
      detail: "V3 → V4 · 新增 2 段 · 删除 1 段",
      reason: "涉及恢复通航窗口，可能更新既有事件 EVT-2026-014。",
      badges: ["重要来源", "已有事件", "证据可定位"],
      action: "review",
    },
    {
      id: "att-port",
      kind: "new",
      priority: "medium",
      title: "Port Said 发布新的等待船舶统计",
      source: "Port Said Authority RSS",
      time: "42 分钟前",
      detail: "新文档 · 1 个独立来源 · 3 个候选主张",
      reason: "可能补充事件 EVT-2026-014 的影响规模，尚无第二来源印证。",
      badges: ["新材料", "待交叉验证"],
      action: "review",
    },
    {
      id: "att-reuters",
      kind: "conflict",
      priority: "high",
      title: "两份材料对恢复时间表述不一致",
      source: "Reuters / SCA",
      time: "1 小时前",
      detail: "2 个独立来源 · 1 条冲突主张",
      reason: "一个来源称“24 小时内”，另一个只确认“正在评估”。",
      badges: ["冲突主张", "需要研判"],
      action: "events",
    },
    {
      id: "att-failure",
      kind: "failure",
      priority: "medium",
      title: "Marine Traffic Bulletin 连续抓取失败",
      source: "Marine Traffic Bulletin",
      time: "2 小时前",
      detail: "连续失败 3 次 · 下一次重试 11:30",
      reason: "原站返回 403。当前专题覆盖不完整，但不会生成伪造数据。",
      badges: ["采集故障", "覆盖缺口"],
      action: "sources",
    },
  ],
  sources: [
    {
      id: "src-sca",
      name: "Suez Canal Authority",
      host: "suezcanal.gov.eg",
      type: "网页",
      method: "HTTP",
      cadence: "30 分钟",
      lastSuccess: "10:42",
      lastChange: "10:42",
      nextRun: "11:12",
      status: "changed",
      health: "healthy",
      lastResult: "changed",
      versions: 4,
      successRate: 98.6,
      failures: 0,
      independence: "官方机构",
      language: "阿拉伯语 / 英语",
    },
    {
      id: "src-port",
      name: "Port Said Authority RSS",
      host: "portsaid.gov.eg",
      type: "RSS",
      method: "RSS + 原页",
      cadence: "15 分钟",
      lastSuccess: "10:39",
      lastChange: "10:18",
      nextRun: "10:54",
      status: "healthy",
      health: "healthy",
      lastResult: "no_change",
      versions: 12,
      successRate: 99.4,
      failures: 0,
      independence: "港口管理方",
      language: "阿拉伯语",
    },
    {
      id: "src-bts",
      name: "BTS Data Spotlight",
      host: "bts.gov",
      type: "网页",
      method: "HTTP",
      cadence: "6 小时",
      lastSuccess: "08:05",
      lastChange: "昨天 17:20",
      nextRun: "14:05",
      status: "healthy",
      health: "healthy",
      lastResult: "no_change",
      versions: 8,
      successRate: 100,
      failures: 0,
      independence: "政府数据",
      language: "英语",
    },
    {
      id: "src-marine",
      name: "Marine Traffic Bulletin",
      host: "marine.example.org",
      type: "网页",
      method: "Browser",
      cadence: "1 小时",
      lastSuccess: "昨天 23:10",
      lastChange: "昨天 18:04",
      nextRun: "11:30",
      status: "failed",
      health: "failed",
      lastResult: "failed",
      versions: 6,
      successRate: 82.1,
      failures: 3,
      independence: "行业媒体",
      language: "英语",
    },
    {
      id: "src-logistics",
      name: "Logistics Delay API",
      host: "api.logistics.example",
      type: "API",
      method: "JSON API",
      cadence: "1 小时",
      lastSuccess: "08:02",
      lastChange: "今天 07:00",
      nextRun: "11:18",
      status: "retrying",
      health: "retrying",
      lastResult: "no_change",
      versions: 21,
      successRate: 91.8,
      failures: 1,
      independence: "商业数据",
      language: "英语",
    },
  ],
  sourceRuns: [
    { id: "run-041", time: "10:42:18", result: "changed", duration: "1.8s", bytes: "84 KB", detail: "V4 已保存，已生成待审项" },
    { id: "run-040", time: "10:12:06", result: "no_change", duration: "1.1s", bytes: "82 KB", detail: "内容哈希未变化" },
    { id: "run-039", time: "09:42:11", result: "no_change", duration: "1.3s", bytes: "82 KB", detail: "内容哈希未变化" },
    { id: "run-038", time: "09:12:04", result: "success", duration: "1.0s", bytes: "82 KB", detail: "V3 已保存" },
  ],
  versions: [
    { id: "V4", time: "今天 10:42", hash: "a93e…72c1", status: "current", run: "run-041" },
    { id: "V3", time: "今天 09:12", hash: "b061…f9a3", status: "previous", run: "run-038" },
    { id: "V2", time: "昨天 18:04", hash: "c8ff…94b0", status: "archived", run: "run-022" },
    { id: "V1", time: "昨天 11:10", hash: "11ae…8c40", status: "archived", run: "run-007" },
  ],
  diff: [
    { type: "same", old: "The Authority confirmed that navigation through the canal remains under controlled coordination.", next: "The Authority confirmed that navigation through the canal remains under controlled coordination." },
    { type: "removed", old: "A full reopening schedule will be announced after the technical assessment is complete.", next: "" },
    { type: "added", old: "", next: "The Authority expects the first northbound convoy to resume within 24 hours, subject to final safety checks." },
    { type: "added", old: "", next: "Priority will be given to vessels carrying medical supplies and perishable cargo." },
    { type: "same", old: "Tug assistance and channel inspections are continuing.", next: "Tug assistance and channel inspections are continuing." },
  ],
  reviewItems: [
    {
      id: "intake-sca-v4",
      status: "candidate_ready",
      type: "内容变化",
      source: "Suez Canal Authority",
      title: "通航恢复时间表更新",
      time: "10:43",
      eventMatch: "EVT-2026-014 · 苏伊士航道恢复评估",
      priority: "high",
      hasSnapshot: true,
      hasCandidate: true,
    },
    {
      id: "intake-port-28",
      status: "candidate_ready",
      type: "新材料",
      source: "Port Said Authority RSS",
      title: "等待船舶统计更新",
      time: "10:19",
      eventMatch: "可能关联 EVT-2026-014",
      priority: "medium",
      hasSnapshot: true,
      hasCandidate: true,
    },
    {
      id: "intake-search-12",
      status: "candidate_ready",
      type: "搜索发现",
      source: "BTS Data Spotlight",
      title: "供应链延迟背景材料",
      time: "09:54",
      eventMatch: "建议新建背景事件",
      priority: "low",
      hasSnapshot: true,
      hasCandidate: true,
    },
    {
      id: "intake-model-fail",
      status: "generation_failed",
      type: "生成失败",
      source: "Logistics Delay API",
      title: "模型返回结构无效",
      time: "08:08",
      eventMatch: "尚未生成候选",
      priority: "medium",
      hasSnapshot: true,
      hasCandidate: false,
      failureStage: "generation",
    },
    {
      id: "intake-fetch-fail",
      status: "failed",
      type: "抓取失败",
      source: "Marine Traffic Bulletin",
      title: "原页面返回 403",
      time: "08:01",
      eventMatch: "正式区未变化",
      priority: "medium",
      hasSnapshot: false,
      hasCandidate: false,
      failureStage: "fetch",
    },
  ],
  candidate: {
    event: {
      title: "苏伊士航道恢复评估",
      summary: "管理局通告新增了受安全检查约束的 24 小时恢复窗口。",
      eventTime: "2026-08-29",
      location: "Suez Canal",
      match: "EVT-2026-014",
    },
    entities: [
      { name: "Suez Canal Authority", type: "organization", role: "发布方" },
      { name: "northbound convoy", type: "operation", role: "受影响对象" },
    ],
    claims: [
      {
        id: "claim-1",
        text: "管理局预计首批北向船队将在 24 小时内恢复通行，但仍取决于最终安全检查。",
        evidence: "The Authority expects the first northbound convoy to resume within 24 hours, subject to final safety checks.",
        stance: "supports",
        strength: 0.86,
        valid: true,
      },
      {
        id: "claim-2",
        text: "医疗物资和易腐货物运输船将被优先安排。",
        evidence: "Priority will be given to vessels carrying medical supplies and perishable cargo.",
        stance: "supports",
        strength: 0.81,
        valid: true,
      },
    ],
    model: {
      name: "glm-5.3-flash",
      latency: "7.4s",
      tokens: "2,184",
      cost: "¥0.04",
      schema: "intake-candidate/v2",
      callId: "llm_01J72D8P",
    },
  },
  reviewDetails: {
    "intake-sca-v4": {
      snapshot: "V4 · a93e…72c1",
      capturedAt: "10:42:18 CST",
      kicker: "Suez Canal Authority · Navigation Update",
      documentTitle: "Statement on the phased resumption of northbound transit",
      intro: "The Authority confirmed that navigation through the canal remains under controlled coordination.",
      outro: "Tug assistance and channel inspections are continuing. Further updates will be published through official channels.",
      diff: "sca",
    },
    "intake-port-28": {
      snapshot: "V1 · d481…0ab2",
      capturedAt: "10:18:44 CST",
      kicker: "Port Said Authority RSS · Vessel Update",
      documentTitle: "Northbound waiting vessel statistics updated",
      intro: "The port authority published an updated operational count for vessels awaiting northbound transit.",
      outro: "The figures are a point-in-time operational count and may change as clearances are issued.",
      candidate: {
        event: {
          title: "苏伊士航道恢复评估",
          summary: "Port Said 的新统计显示，北向等待船舶为 37 艘，其中 9 艘运输易腐货物。",
          eventTime: "2026-08-29",
          location: "Port Said",
          match: "EVT-2026-014",
        },
        entities: [
          { name: "Port Said Authority", type: "organization", role: "发布方" },
          { name: "37 waiting vessels", type: "measurement", role: "影响规模" },
        ],
        claims: [
          {
            id: "port-claim-1",
            text: "Port Said 管理方记录到 37 艘船等待北向通行。",
            evidence: "A total of 37 vessels were recorded waiting for northbound transit at 10:00 local time.",
            stance: "supports",
            strength: 0.84,
            valid: true,
          },
          {
            id: "port-claim-2",
            text: "等待船舶中有 9 艘运输易腐货物。",
            evidence: "Nine of the waiting vessels were carrying perishable cargo.",
            stance: "supports",
            strength: 0.82,
            valid: true,
          },
        ],
        model: {
          name: "glm-5.3-flash",
          latency: "6.8s",
          tokens: "1,746",
          cost: "¥0.03",
          schema: "intake-candidate/v2",
          callId: "llm_01J72E1M",
        },
      },
    },
    "intake-search-12": {
      snapshot: "V1 · 5c11…92fe",
      capturedAt: "09:53:26 CST",
      kicker: "BTS Data Spotlight · Search Discovery",
      documentTitle: "Canal disruptions and downstream freight delay",
      intro: "Historical transportation data shows that canal disruptions can affect downstream freight schedules beyond the initial closure window.",
      outro: "This material provides background context and does not independently confirm the current Suez event.",
      candidate: {
        event: {
          title: "航道中断后的下游物流延迟",
          summary: "背景材料说明航道扰动可能在恢复通行后继续影响下游班期；它不直接证明当前事件的实际延迟。",
          eventTime: "2026-08-29",
          location: "Global maritime routes",
          match: "建议新建背景事件",
        },
        entities: [
          { name: "Bureau of Transportation Statistics", type: "organization", role: "数据发布方" },
          { name: "downstream freight schedules", type: "concept", role: "背景对象" },
        ],
        claims: [
          {
            id: "bts-claim-1",
            text: "历史数据表明，航道恢复后，下游货运班期仍可能继续受到影响。",
            evidence: "Downstream freight schedules may remain affected after traffic through a constrained waterway resumes.",
            stance: "context",
            strength: 0.72,
            valid: true,
          },
        ],
        model: {
          name: "glm-5.3-flash",
          latency: "5.9s",
          tokens: "1,208",
          cost: "¥0.02",
          schema: "intake-candidate/v2",
          callId: "llm_01J72E4Q",
        },
      },
    },
    "intake-model-fail": {
      snapshot: "V21 · f621…119d",
      capturedAt: "08:02:19 CST",
      kicker: "Logistics Delay API · Validated JSON",
      documentTitle: "Latest logistics delay measurements",
      intro: "The upstream API response passed schema validation and was stored as snapshot V21.",
      outro: "Candidate generation failed because the model response did not match intake-candidate/v2. The source snapshot remains available for inspection.",
      evidence: ["Average reported delay: 18.4 hours across the selected maritime corridor."],
    },
  },
  event: {
    id: "EVT-2026-014",
    title: "苏伊士航道恢复评估",
    status: "已确认 · 持续更新",
    summary: "在完成拖带与航道检查后，管理局开始评估分阶段恢复北向船队的条件。",
    time: "2026-08-28 — 进行中",
    location: "Suez Canal, Egypt",
    documents: 6,
    sources: 4,
    claims: 5,
    evidence: 11,
    confidence: "中等",
  },
};

window.PLDR_MOCK_DATA = PLDR_MOCK_DATA;
